import axios from "axios";

export async function fetchNodes() {
    return await axios.get("http://localhost:8081/nos");
}

export const initialNodes = [
    {
        id: "1",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "2",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "3",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "4",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "5",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "6",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "7",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "8",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "9",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "10",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "11",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "12",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "13",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "14",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "15",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "16",
        tipo: "ub",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#0076b2",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "17",
        tipo: "pa",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#dd00ff",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "18",
        tipo: "pa",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#dd00ff",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
    {
        id: "19",
        tipo: "pt",
        data: {},
        style: {
            borderRadius: "50%",
            background: "#dd00ff",
        },
        width: 30,
        height: 30,
        selected: false,
        draggable: true,
        sourcePosition: "right",
        targetPosition: "left",
    },
];
